apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: flask-app
  selector:
    app: flask
  type: LoadBalancer
